SET SERVEROUTPUT ON;

DECLARE 
A NUMBER := 10;
B NUMBER := 0;
C NUMBER ;

BEGIN 
C :=A / B;
DBMS_OUTPUT.PUT_LINE('RESULT = ' || C);

EXCEPTION 
WHEN ZERO_DIVIDE THEN 
    DBMS_OUTPUT.PUT_LINE('ERROR: Cannot Devide by zero');
END;
/